DB:
  PG_HOST: xxxx
  PG_HOST_REPLICA: xxx
  PG_USER: xxxx
  PG_DB: xxxx
  PG_PORT: xxx
  PG_PORT_REPLICA: xxx
  PG_PASS: xxx
  PG_CONN_MAX_IDLE_TIME: xxx
  PG_CONN_MAX_LIFE_TIME: xxx
  PG_MAX_IDLE_CONN: 2
  PG_MAX_OPEN_CONN: 2
  
